[package]
name = "snarkvm-synthesizer-program"
version = "0.9.13"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Definitions, parsing and (de)serialization for programs on a decentralized virtual machine."
license = "GPL-3.0"
edition = "2021"

[dependencies.circuit]
package = "snarkvm-circuit"
path = "../../circuit"
version = "0.9.13"

[dependencies.console]
package = "snarkvm-console"
path = "../../console"
version = "0.9.13"

[dependencies.indexmap]
version = "1.9"
features = [ "serde", "rayon" ]

[dependencies.paste]
version = "1.0.11"

[dependencies.rand]
version = "0.8"
