[package]
name = "snarkvm-synthesizer-program"
version = "0.11.7"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A program for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [
  "compilers",
  "cryptography",
  "mathematics",
  "wasm",
  "web-programming"
]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "Apache-2.0"
edition = "2021"

[features]
default = [ ]
serial = [ "console/serial" ]
wasm = [ "console/wasm" ]

[dependencies.circuit]
package = "snarkvm-circuit"
path = "../../circuit"
version = "=0.11.7"

[dependencies.console]
package = "snarkvm-console"
path = "../../console"
version = "=0.11.7"
default-features = false
features = [ "network", "program", "types" ]

[dependencies.indexmap]
version = "1.9"
features = [ "serde", "rayon" ]

[dependencies.parking_lot]
version = "0.12"

[dependencies.paste]
version = "1.0.12"

[dependencies.rand]
version = "0.8"

[dev-dependencies.bincode]
version = "1"

[dev-dependencies.serde_json]
version = "1.0"
features = [ "preserve_order" ]

[dev-dependencies.snarkvm-synthesizer]
path = ".."

[dev-dependencies.snarkvm-synthesizer-snark]
path = "../snark"

#[dev-dependencies.console]
#package = "snarkvm-console"
#path = "../../console"
#default-features = false
#features = [ "types" ]
