[package]
name = "snarkvm-ledger-narwhal"
version = "0.14.5"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Data structures for a Narwhal-style memory pool in a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkVM"
keywords = [
    "aleo",
    "cryptography",
    "blockchain",
    "decentralized",
    "zero-knowledge"
]
categories = [
    "compilers",
    "cryptography",
    "mathematics",
    "wasm",
    "web-programming"
]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "Apache-2.0"
edition = "2021"

[features]
default = [ "batch-certificate", "batch-header", "transmission", "transmission-id" ]
serial = [ "console/serial" ]
wasm = [ "console/wasm" ]
test-helpers = [ "bytes", "time" ]

batch-certificate = [ "batch-header", "console", "indexmap", "serde_json", "transmission-id" ]
batch-header = [ "console", "indexmap", "transmission-id" ]
transmission = [ "bytes", "ledger-block", "ledger-coinbase" ]
transmission-id = [ "console", "ledger-coinbase" ]

[dependencies.console]
package = "snarkvm-console"
path = "../../console"
version = "=0.14.5"
optional = true

[dependencies.ledger-block]
package = "snarkvm-ledger-block"
path = "../../ledger/block"
version = "=0.14.5"
optional = true

[dependencies.ledger-coinbase]
package = "snarkvm-ledger-coinbase"
path = "../../ledger/coinbase"
version = "=0.14.5"
optional = true

[dependencies.bytes]
version = "1"
optional = true

[dependencies.indexmap]
version = "2.0"
features = [ "serde" ]
optional = true

[dependencies.serde_json]
version = "1.0"
optional = true
features = [ "preserve_order" ]

[dependencies.time]
version = "0.3"
optional = true

[dev-dependencies.bincode]
version = "1.3"

[dev-dependencies.rand]
version = "0.8"

[dev-dependencies.serde_json]
version = "1.0"
features = [ "preserve_order" ]

[dev-dependencies.snarkvm-ledger-narwhal]
path = "."
features = [ "test-helpers" ]
